name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: install uv
        uses: astral-sh/setup-uv@v4

      - uses: actions/checkout@v4

      - name: sync
        run: uv sync --all-extras --dev

      - name: ruff check
        run: uv run ruff check

      - name: ruff format check
        run: uv run ruff format --check

      - name: pylint
        run: uv run pylint src

      - name: bandit
        run: uv run bandit -r src

      - name: vulture
        run: uv run vulture src || true

      - name: mypy
        run: uv run mypy src

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: install uv
        uses: astral-sh/setup-uv@v4

      - uses: actions/checkout@v4

      - name: sync
        run: uv sync --all-extras --dev

      - name: pytest
        run: uv run pytest
